version: '3.7'
services:
    nginx:
      image: nginx:alpine
      container_name: docker-project-nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 89:80
    php-fpm:
      build: docker/php-fpm
      container_name: docker-project-php-fpm
      working_dir: /application
      volumes:
        - .:/application
    database:
      image: mysql:latest
      container_name: docker-project-database
      volumes:
        - ./docker/database:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
      ports:
        - ${DB_PORT}:3306
